# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('member_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='member_photos/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(choices=[('pending', 'Pending Registration'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('submitted', 'Request Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended'), ('dormant', 'Dormant'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=50)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('membership_fee_paid', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members',
                'indexes': [models.Index(fields=['cooperative_id', 'status'], name='members_coopera_50296b_idx'), models.Index(fields=['cooperative_id', 'member_number'], name='members_coopera_04a3d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID/NIDA'), ('passport', 'Passport'), ('voters_id', 'Voter ID'), ('drivers_license', 'Drivers License'), ('passport_photo', 'Passport Photo'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('letter', 'Introduction Letter'), ('other', 'Other')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='kyc_documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='members.member')),
            ],
            options={
                'db_table': 'kyc_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='members.member')),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_loan_multiplier', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member_categories',
                'unique_together': {('cooperative_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kins', to='members.member')),
            ],
            options={
                'db_table': 'next_of_kins',
            },
        ),
    ]
