# Generated by Django 6.0.5 on 2026-05-16 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('normal', 'Normal / First Issue'), ('replacement', 'Replacement / Repeat')], default='normal', max_length=20)),
                ('issued_by', models.BigIntegerField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_issuances', to='members.member')),
            ],
            options={
                'db_table': 'card_issuances',
                'ordering': ['-issued_at'],
            },
        ),
    ]
