# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('nomination_start', models.DateField()),
                ('nomination_end', models.DateField()),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('nomination', 'Nomination Phase'), ('campaign', 'Campaign Phase'), ('voting', 'Voting Phase'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('annual_general', 'Annual General Meeting'), ('board', 'Board Meeting'), ('committee', 'Committee Meeting'), ('special', 'Special Meeting'), ('emergency', 'Emergency Meeting')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=50)),
                ('organized_by', models.BigIntegerField()),
                ('minutes', models.TextField(blank=True)),
                ('minutes_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('member_name', models.CharField(max_length=255)),
                ('manifesto', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='candidates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='governance.election')),
            ],
            options={
                'db_table': 'candidates',
                'unique_together': {('election', 'member_id')},
            },
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='meeting_docs/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='governance.meeting')),
            ],
            options={
                'db_table': 'meeting_documents',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposed_by', models.BigIntegerField()),
                ('seconded_by', models.BigIntegerField(blank=True, null=True)),
                ('votes_for', models.IntegerField(default=0)),
                ('votes_against', models.IntegerField(default=0)),
                ('votes_abstain', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('implemented', models.BooleanField(default=False)),
                ('implementation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='governance.meeting')),
            ],
            options={
                'db_table': 'resolutions',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('member_name', models.CharField(max_length=255)),
                ('attended', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='governance.meeting')),
            ],
            options={
                'db_table': 'meeting_attendance',
                'unique_together': {('meeting', 'member_id')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.election')),
            ],
            options={
                'db_table': 'votes',
                'unique_together': {('election', 'member_id')},
            },
        ),
    ]
