# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('member', 'Member Report'), ('savings', 'Savings Report'), ('loan', 'Loan Report'), ('accounting', 'Accounting Report'), ('governance', 'Governance Report'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('generated_by', models.BigIntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.reporttemplate')),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
