# Generated by Django 6.0.5 on 2026-05-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_bill_number_invoice_control_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Member submitted at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto API'), ('ussd', 'USSD Code')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transaction/USSD Code'),
        ),
    ]
