# Generated by Django 6.0.5 on 2026-05-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_sms_sent_payment_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('registration_fee', 'Registration Fee'), ('membership_fee', 'Membership Fee'), ('share_purchase', 'Share Purchase'), ('savings_deposit', 'Savings Deposit'), ('loan_repayment', 'Loan Repayment'), ('loan_disbursement', 'Loan Disbursement'), ('subscription', 'Subscription'), ('contribution', 'Contribution'), ('fine', 'Fine/Penalty'), ('withdrawal', 'Withdrawal'), ('dividend', 'Dividend'), ('other', 'Other')], max_length=50),
        ),
    ]
