# Generated by Django 6.0.5 on 2026-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepaymentrequest',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa')], max_length=50),
        ),
    ]
