# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('voluntary', 'Voluntary Savings'), ('mandatory', 'Mandatory Savings'), ('fixed_deposit', 'Fixed Deposit'), ('special', 'Special Savings')], default='voluntary', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('interest_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('freeze_reason', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'savings_accounts',
                'indexes': [models.Index(fields=['cooperative_id', 'member_id'], name='savings_acc_coopera_1edd65_idx'), models.Index(fields=['account_number'], name='savings_acc_account_fc7e98_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('correction', 'Correction')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount')),
            ],
            options={
                'db_table': 'savings_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='savings_tra_account_b3577f_idx'), models.Index(fields=['cooperative_id', 'transaction_type'], name='savings_tra_coopera_85c218_idx')],
            },
        ),
    ]
