# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('loan_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_method', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance')], default='flat', max_length=50)),
                ('duration_months', models.IntegerField()),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('officer_review', 'Loan Officer Review'), ('financial_review', 'Financial Review'), ('chairperson_approval', 'Chairperson Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('restructured', 'Restructured'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=50)),
                ('purpose', models.TextField(blank=True)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_by', models.BigIntegerField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_method', models.CharField(blank=True, max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('default_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='loan_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_documents',
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_member_id', models.BigIntegerField(db_index=True)),
                ('guarantor_name', models.CharField(max_length=255)),
                ('guarantor_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_guarantors',
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_method', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance')], default='flat', max_length=50)),
                ('min_duration_months', models.IntegerField(default=1)),
                ('max_duration_months', models.IntegerField(default=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('num_guarantors_required', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loan_products',
                'unique_together': {('cooperative_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanproduct'),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_on_time', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['cooperative_id', 'status'], name='loans_coopera_8705fa_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member_id', 'status'], name='loans_member__0153ae_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='loans_loan_nu_a48674_idx'),
        ),
    ]
