# Generated by Django 6.0.5 on 2026-05-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('agricultural_crops', 'Agricultural Crops (Mazao)'), ('tractors', 'Tractors'), ('farming_equipment', 'Farming Equipment & Assets')], default='general', max_length=50),
        ),
    ]
