# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('financial_year', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('per_share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dividends',
                'ordering': ['-financial_year'],
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField()),
                ('share_id', models.BigIntegerField()),
                ('shares_owned', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shares.dividend')),
            ],
            options={
                'db_table': 'dividend_payments',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('total_shares', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shares',
                'unique_together': {('cooperative_id', 'member_id')},
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('member_id', models.BigIntegerField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('bonus', 'Bonus Issue'), ('dividend', 'Dividend Reinvestment')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shares.share')),
            ],
            options={
                'db_table': 'share_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
