# Generated by Django 6.0.5 on 2026-05-15 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('check_type', models.CharField(choices=[('kyc', 'KYC Compliance'), ('financial', 'Financial Compliance'), ('regulatory', 'Regulatory Compliance'), ('tax', 'Tax Compliance'), ('governance', 'Governance Compliance'), ('data_protection', 'Data Protection')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', max_length=50)),
                ('findings', models.TextField(blank=True)),
                ('checked_by', models.BigIntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='new', max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('detected_by', models.BigIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investigated_by', models.BigIntegerField(blank=True, null=True)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative_id', 'entity_type', 'entity_id'], name='audit_trail_coopera_7fc871_idx'), models.Index(fields=['user_id', 'action'], name='audit_trail_user_id_52a6da_idx')],
            },
        ),
    ]
