# Generated by Django 6.0.5 on 2026-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('cooperative_admin', 'Cooperative Admin'), ('chairperson', 'Mwenyekiti'), ('secretary', 'Katibu'), ('treasurer', 'Mhazini'), ('accountant', 'Mhasibu'), ('board_member', 'Mjumbe wa Bodi'), ('carder', 'Carder / ID Officer'), ('member', 'Mwanachama/Mkulima')], default='member', max_length=50),
        ),
    ]
